In [15]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [4]:
zero_arr = np.zeros((3, 3))
print(zero_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
arr2 = np.arange(0, 21)
print(arr2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [7]:
arr3 = np.array([[1,2,3],
          [4,5,6]])

In [11]:
print(arr3.shape)

print(arr3.ndim)
print(arr3.size)

(2, 3)
2
6


In [17]:
print(arr[1:5])

[2 3 4 5]


In [19]:
print(arr+10)
print(arr * 3)

[11 12 13 14 15 16 17 18 19 20]
[ 3  6  9 12 15 18 21 24 27 30]


In [20]:
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.sum(arr))

1
10
5.5
55


In [24]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])
arr4 = np.reshape(arr4, (4, 4))
print(arr4)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


Boolean Masking

In [25]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)

[False False  True  True  True]


In [26]:
print(arr[arr>25])

[30 40 50]


In [27]:
arr = np.array([10,20,30,40,50,60])

print(arr[(arr > 20) & (arr < 60)])

[30 40 50]


Fancy Indexing

In [28]:
arr = np.array([100,200,300,400,500])

print(arr[[0,2,4]])

[100 300 500]


Flattening Array

In [29]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.flatten())

[1 2 3 4 5 6]


Transpose

In [30]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


Random Numbers

In [31]:
np.random.rand(5)

array([0.78361117, 0.26704363, 0.2546481 , 0.7400589 , 0.3654333 ])

In [32]:
np.random.randint(1, 100, 5)

array([30, 64,  3, 48, 93])

Axis Operations

In [33]:
arr = np.array([
    [1,2,3],
    [4,5,6]
])
print(np.sum(arr, axis =0))
print(np.sum(arr, axis = 1))

[5 7 9]
[ 6 15]


Stacking Arrays

In [35]:
a = np.array([1,2,3])
b = np.array([4,5,6])

np.vstack((a,b))
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6])

In [1]:
import numpy as np

arr = np.array([20,40,60,80,100])

normalized = (arr - arr.min()) / (arr.max() - arr.min())

print(normalized)

[0.   0.25 0.5  0.75 1.  ]
